<?php

namespace AG\CountryList;
use DateTime;
use DateTimeZone;

enum Country: string
{
    case UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'um';
    case NIUE = 'nu';
    case AMERICAN_SAMOA = 'as';
    case UNITED_STATES = 'us';
    case COOK_ISLANDS = 'ck';
    case FRENCH_POLYNESIA = 'pf';
    case CANADA = 'ca';
    case PITCAIRN_ISLANDS = 'pn';
    case MEXICO = 'mx';
    case BELIZE = 'bz';
    case COSTA_RICA = 'cr';
    case CHILE = 'cl';
    case EL_SALVADOR = 'sv';
    case ECUADOR = 'ec';
    case GUATEMALA = 'gt';
    case NICARAGUA = 'ni';
    case HONDURAS = 'hn';
    case COLOMBIA = 'co';
    case CAYMAN_ISLANDS = 'ky';
    case TURKS_AND_CAICOS_ISLANDS = 'tc';
    case CUBA = 'cu';
    case JAMAICA = 'jm';
    case PERU = 'pe';
    case BAHAMAS = 'bs';
    case PANAMA = 'pa';
    case HAITI = 'ht';
    case VENEZUELA = 've';
    case ANGUILLA = 'ai';
    case ANTIGUA_AND_BARBUDA = 'ag';
    case ARUBA = 'aw';
    case PARAGUAY = 'py';
    case BARBADOS = 'bb';
    case BERMUDA = 'bm';
    case BRAZIL = 'br';
    case CURACAO = 'cw';
    case DOMINICA = 'dm';
    case GRENADA = 'gd';
    case GUADELOUPE = 'gp';
    case GUYANA = 'gy';
    case CARIBBEAN_NETHERLANDS = 'bq';
    case BOLIVIA = 'bo';
    case SINT_MAARTEN = 'sx';
    case SAINT_MARTIN = 'mf';
    case MARTINIQUE = 'mq';
    case MONTSERRAT = 'ms';
    case ANTARCTICA = 'aq';
    case TRINIDAD_AND_TOBAGO = 'tt';
    case PUERTO_RICO = 'pr';
    case DOMINICAN_REPUBLIC = 'do';
    case SAINT_BARTHELEMY = 'bl';
    case SAINT_KITTS_AND_NEVIS = 'kn';
    case SAINT_LUCIA = 'lc';
    case UNITED_STATES_VIRGIN_ISLANDS = 'vi';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'vc';
    case GREENLAND = 'gl';
    case BRITISH_VIRGIN_ISLANDS = 'vg';
    case ARGENTINA = 'ar';
    case FRENCH_GUIANA = 'gf';
    case SAINT_PIERRE_AND_MIQUELON = 'pm';
    case URUGUAY = 'uy';
    case SURINAME = 'sr';
    case FALKLAND_ISLANDS = 'fk';
    case SOUTH_GEORGIA = 'gs';
    case PORTUGAL = 'pt';
    case CAPE_VERDE = 'cv';
    case COTE_DIVOIRE = 'ci';
    case GHANA = 'gh';
    case MALI = 'ml';
    case GAMBIA = 'gm';
    case GUINEA_BISSAU = 'gw';
    case SPAIN = 'es';
    case MOROCCO = 'ma';
    case GUINEA = 'gn';
    case SENEGAL = 'sn';
    case IRELAND = 'ie';
    case WESTERN_SAHARA = 'eh';
    case FAROE_ISLANDS = 'fo';
    case SIERRA_LEONE = 'sl';
    case GUERNSEY = 'gg';
    case ISLE_OF_MAN = 'im';
    case JERSEY = 'je';
    case TOGO = 'tg';
    case UNITED_KINGDOM = 'gb';
    case ENGLAND = 'gb-eng';
    case NORTHERN_IRELAND = 'gb-nir';
    case SCOTLAND = 'gb-sct';
    case WALES = 'gb-wls';
    case LIBERIA = 'lr';
    case MAURITANIA = 'mr';
    case BURKINA_FASO = 'bf';
    case ICELAND = 'is';
    case SAO_TOME_AND_PRINCIPE = 'st';
    case SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = 'sh';
    case ALGERIA = 'dz';
    case NETHERLANDS = 'nl';
    case ANDORRA = 'ad';
    case CENTRAL_AFRICAN_REPUBLIC = 'cf';
    case SERBIA = 'rs';
    case GERMANY = 'de';
    case SLOVAKIA = 'sk';
    case REPUBLIC_OF_THE_CONGO = 'cg';
    case BELGIUM = 'be';
    case HUNGARY = 'hu';
    case DENMARK = 'dk';
    case CAMEROON = 'cm';
    case GIBRALTAR = 'gi';
    case DR_CONGO = 'cd';
    case NIGERIA = 'ng';
    case GABON = 'ga';
    case SLOVENIA = 'si';
    case SVALBARD_AND_JAN_MAYEN = 'sj';
    case ANGOLA = 'ao';
    case LUXEMBOURG = 'lu';
    case EQUATORIAL_GUINEA = 'gq';
    case MALTA = 'mt';
    case MONACO = 'mc';
    case CHAD = 'td';
    case NIGER = 'ne';
    case NORWAY = 'no';
    case FRANCE = 'fr';
    case MONTENEGRO = 'me';
    case BENIN = 'bj';
    case CZECHIA = 'cz';
    case ITALY = 'it';
    case SAN_MARINO = 'sm';
    case BOSNIA_AND_HERZEGOVINA = 'ba';
    case NORTH_MACEDONIA = 'mk';
    case SWEDEN = 'se';
    case ALBANIA = 'al';
    case LIBYA = 'ly';
    case TUNISIA = 'tn';
    case LIECHTENSTEIN = 'li';
    case VATICAN_CITY = 'va';
    case AUSTRIA = 'at';
    case POLAND = 'pl';
    case NAMIBIA = 'na';
    case CROATIA = 'hr';
    case SWITZERLAND = 'ch';
    case GREECE = 'gr';
    case LEBANON = 'lb';
    case MALAWI = 'mw';
    case ROMANIA = 'ro';
    case BURUNDI = 'bi';
    case EGYPT = 'eg';
    case MOLDOVA = 'md';
    case SYRIA = 'sy';
    case BOTSWANA = 'bw';
    case PALESTINE = 'ps';
    case ZIMBABWE = 'zw';
    case FINLAND = 'fi';
    case TURKEY = 'tr';
    case ISRAEL = 'il';
    case SOUTH_AFRICA = 'za';
    case RWANDA = 'rw';
    case ZAMBIA = 'zm';
    case MOZAMBIQUE = 'mz';
    case ALAND_ISLANDS = 'ax';
    case LESOTHO = 'ls';
    case ESWATINI = 'sz';
    case CYPRUS = 'cy';
    case LATVIA = 'lv';
    case UKRAINE = 'ua';
    case BULGARIA = 'bg';
    case ESTONIA = 'ee';
    case LITHUANIA = 'lt';
    case ETHIOPIA = 'et';
    case YEMEN = 'ye';
    case JORDAN = 'jo';
    case MADAGASCAR = 'mg';
    case ERITREA = 'er';
    case IRAQ = 'iq';
    case BAHRAIN = 'bh';
    case COMOROS = 'km';
    case TANZANIA = 'tz';
    case DJIBOUTI = 'dj';
    case SOUTH_SUDAN = 'ss';
    case RUSSIA = 'ru';
    case UGANDA = 'ug';
    case SUDAN = 'sd';
    case KUWAIT = 'kw';
    case MAYOTTE = 'yt';
    case BELARUS = 'by';
    case SOMALIA = 'so';
    case KENYA = 'ke';
    case QATAR = 'qa';
    case SAUDI_ARABIA = 'sa';
    case IRAN = 'ir';
    case AZERBAIJAN = 'az';
    case UNITED_ARAB_EMIRATES = 'ae';
    case SEYCHELLES = 'sc';
    case MAURITIUS = 'mu';
    case OMAN = 'om';
    case REUNION = 're';
    case GEORGIA = 'ge';
    case ARMENIA = 'am';
    case AFGHANISTAN = 'af';
    case KAZAKHSTAN = 'kz';
    case TURKMENISTAN = 'tm';
    case TAJIKISTAN = 'tj';
    case PAKISTAN = 'pk';
    case FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS = 'tf';
    case MALDIVES = 'mv';
    case UZBEKISTAN = 'uz';
    case SRI_LANKA = 'lk';
    case INDIA = 'in';
    case NEPAL = 'np';
    case KYRGYZSTAN = 'kg';
    case BRITISH_INDIAN_OCEAN_TERRITORY = 'io';
    case BANGLADESH = 'bd';
    case BHUTAN = 'bt';
    case COCOS_ISLANDS = 'cc';
    case THAILAND = 'th';
    case CHRISTMAS_ISLAND = 'cx';
    case VIETNAM = 'vn';
    case MONGOLIA = 'mn';
    case INDONESIA = 'id';
    case CAMBODIA = 'kh';
    case LAOS = 'la';
    case BRUNEI = 'bn';
    case HONG_KONG = 'hk';
    case MALAYSIA = 'my';
    case MACAU = 'mo';
    case PHILIPPINES = 'ph';
    case AUSTRALIA = 'au';
    case CHINA = 'cn';
    case SINGAPORE = 'sg';
    case TAIWAN = 'tw';
    case TIMOR_LESTE = 'tl';
    case PALAU = 'pw';
    case NORTH_KOREA = 'kp';
    case SOUTH_KOREA = 'kr';
    case JAPAN = 'jp';
    case MICRONESIA = 'fm';
    case GUAM = 'gu';
    case PAPUA_NEW_GUINEA = 'pg';
    case NORTHERN_MARIANA_ISLANDS = 'mp';
    case VANUATU = 'vu';
    case SOLOMON_ISLANDS = 'sb';
    case NEW_CALEDONIA = 'nc';
    case NORFOLK_ISLAND = 'nf';
    case NEW_ZEALAND = 'nz';
    case FIJI = 'fj';
    case TUVALU = 'tv';
    case MARSHALL_ISLANDS = 'mh';
    case NAURU = 'nr';
    case KIRIBATI = 'ki';
    case WALLIS_AND_FUTUNA = 'wf';
    case SAMOA = 'ws';
    case TOKELAU = 'tk';
    case TONGA = 'to';

    public function getName(): string
    {
        return match ($this) {
            self::UNITED_STATES_MINOR_OUTLYING_ISLANDS => "United States Minor Outlying Islands",
            self::NIUE => "Niue",
            self::AMERICAN_SAMOA => "American Samoa",
            self::UNITED_STATES => "United States",
            self::COOK_ISLANDS => "Cook Islands",
            self::FRENCH_POLYNESIA => "French Polynesia",
            self::CANADA => "Canada",
            self::PITCAIRN_ISLANDS => "Pitcairn Islands",
            self::MEXICO => "Mexico",
            self::BELIZE => "Belize",
            self::COSTA_RICA => "Costa Rica",
            self::CHILE => "Chile",
            self::EL_SALVADOR => "El Salvador",
            self::ECUADOR => "Ecuador",
            self::GUATEMALA => "Guatemala",
            self::NICARAGUA => "Nicaragua",
            self::HONDURAS => "Honduras",
            self::COLOMBIA => "Colombia",
            self::CAYMAN_ISLANDS => "Cayman Islands",
            self::TURKS_AND_CAICOS_ISLANDS => "Turks and Caicos Islands",
            self::CUBA => "Cuba",
            self::JAMAICA => "Jamaica",
            self::PERU => "Peru",
            self::BAHAMAS => "Bahamas",
            self::PANAMA => "Panama",
            self::HAITI => "Haiti",
            self::VENEZUELA => "Venezuela",
            self::ANGUILLA => "Anguilla",
            self::ANTIGUA_AND_BARBUDA => "Antigua and Barbuda",
            self::ARUBA => "Aruba",
            self::PARAGUAY => "Paraguay",
            self::BARBADOS => "Barbados",
            self::BERMUDA => "Bermuda",
            self::BRAZIL => "Brazil",
            self::CURACAO => "Curaçao",
            self::DOMINICA => "Dominica",
            self::GRENADA => "Grenada",
            self::GUADELOUPE => "Guadeloupe",
            self::GUYANA => "Guyana",
            self::CARIBBEAN_NETHERLANDS => "Caribbean Netherlands",
            self::BOLIVIA => "Bolivia",
            self::SINT_MAARTEN => "Sint Maarten",
            self::SAINT_MARTIN => "Saint Martin",
            self::MARTINIQUE => "Martinique",
            self::MONTSERRAT => "Montserrat",
            self::ANTARCTICA => "Antarctica",
            self::TRINIDAD_AND_TOBAGO => "Trinidad and Tobago",
            self::PUERTO_RICO => "Puerto Rico",
            self::DOMINICAN_REPUBLIC => "Dominican Republic",
            self::SAINT_BARTHELEMY => "Saint Barthélemy",
            self::SAINT_KITTS_AND_NEVIS => "Saint Kitts and Nevis",
            self::SAINT_LUCIA => "Saint Lucia",
            self::UNITED_STATES_VIRGIN_ISLANDS => "United States Virgin Islands",
            self::SAINT_VINCENT_AND_THE_GRENADINES => "Saint Vincent and the Grenadines",
            self::GREENLAND => "Greenland",
            self::BRITISH_VIRGIN_ISLANDS => "British Virgin Islands",
            self::ARGENTINA => "Argentina",
            self::FRENCH_GUIANA => "French Guiana",
            self::SAINT_PIERRE_AND_MIQUELON => "Saint Pierre and Miquelon",
            self::URUGUAY => "Uruguay",
            self::SURINAME => "Suriname",
            self::FALKLAND_ISLANDS => "Falkland Islands",
            self::SOUTH_GEORGIA => "South Georgia",
            self::PORTUGAL => "Portugal",
            self::CAPE_VERDE => "Cape Verde",
            self::COTE_DIVOIRE => "Côte d'Ivoire (Ivory Coast)",
            self::GHANA => "Ghana",
            self::MALI => "Mali",
            self::GAMBIA => "Gambia",
            self::GUINEA_BISSAU => "Guinea-Bissau",
            self::SPAIN => "Spain",
            self::MOROCCO => "Morocco",
            self::GUINEA => "Guinea",
            self::SENEGAL => "Senegal",
            self::IRELAND => "Ireland",
            self::WESTERN_SAHARA => "Western Sahara",
            self::FAROE_ISLANDS => "Faroe Islands",
            self::SIERRA_LEONE => "Sierra Leone",
            self::GUERNSEY => "Guernsey",
            self::ISLE_OF_MAN => "Isle of Man",
            self::JERSEY => "Jersey",
            self::TOGO => "Togo",
            self::UNITED_KINGDOM => "United Kingdom",
            self::ENGLAND => "England",
            self::NORTHERN_IRELAND => "Northern Ireland",
            self::SCOTLAND => "Scotland",
            self::WALES => "Wales",
            self::LIBERIA => "Liberia",
            self::MAURITANIA => "Mauritania",
            self::BURKINA_FASO => "Burkina Faso",
            self::ICELAND => "Iceland",
            self::SAO_TOME_AND_PRINCIPE => "São Tomé and Príncipe",
            self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA => "Saint Helena, Ascension and Tristan da Cunha",
            self::ALGERIA => "Algeria",
            self::NETHERLANDS => "Netherlands",
            self::ANDORRA => "Andorra",
            self::CENTRAL_AFRICAN_REPUBLIC => "Central African Republic",
            self::SERBIA => "Serbia",
            self::GERMANY => "Germany",
            self::SLOVAKIA => "Slovakia",
            self::REPUBLIC_OF_THE_CONGO => "Republic of the Congo",
            self::BELGIUM => "Belgium",
            self::HUNGARY => "Hungary",
            self::DENMARK => "Denmark",
            self::CAMEROON => "Cameroon",
            self::GIBRALTAR => "Gibraltar",
            self::DR_CONGO => "DR Congo",
            self::NIGERIA => "Nigeria",
            self::GABON => "Gabon",
            self::SLOVENIA => "Slovenia",
            self::SVALBARD_AND_JAN_MAYEN => "Svalbard and Jan Mayen",
            self::ANGOLA => "Angola",
            self::LUXEMBOURG => "Luxembourg",
            self::EQUATORIAL_GUINEA => "Equatorial Guinea",
            self::MALTA => "Malta",
            self::MONACO => "Monaco",
            self::CHAD => "Chad",
            self::NIGER => "Niger",
            self::NORWAY => "Norway",
            self::FRANCE => "France",
            self::MONTENEGRO => "Montenegro",
            self::BENIN => "Benin",
            self::CZECHIA => "Czechia",
            self::ITALY => "Italy",
            self::SAN_MARINO => "San Marino",
            self::BOSNIA_AND_HERZEGOVINA => "Bosnia and Herzegovina",
            self::NORTH_MACEDONIA => "North Macedonia",
            self::SWEDEN => "Sweden",
            self::ALBANIA => "Albania",
            self::LIBYA => "Libya",
            self::TUNISIA => "Tunisia",
            self::LIECHTENSTEIN => "Liechtenstein",
            self::VATICAN_CITY => "Vatican City (Holy See)",
            self::AUSTRIA => "Austria",
            self::POLAND => "Poland",
            self::NAMIBIA => "Namibia",
            self::CROATIA => "Croatia",
            self::SWITZERLAND => "Switzerland",
            self::GREECE => "Greece",
            self::LEBANON => "Lebanon",
            self::MALAWI => "Malawi",
            self::ROMANIA => "Romania",
            self::BURUNDI => "Burundi",
            self::EGYPT => "Egypt",
            self::MOLDOVA => "Moldova",
            self::SYRIA => "Syria",
            self::BOTSWANA => "Botswana",
            self::PALESTINE => "Palestine",
            self::ZIMBABWE => "Zimbabwe",
            self::FINLAND => "Finland",
            self::TURKEY => "Turkey",
            self::ISRAEL => "Israel",
            self::SOUTH_AFRICA => "South Africa",
            self::RWANDA => "Rwanda",
            self::ZAMBIA => "Zambia",
            self::MOZAMBIQUE => "Mozambique",
            self::ALAND_ISLANDS => "Åland Islands",
            self::LESOTHO => "Lesotho",
            self::ESWATINI => "Eswatini (Swaziland)",
            self::CYPRUS => "Cyprus",
            self::LATVIA => "Latvia",
            self::UKRAINE => "Ukraine",
            self::BULGARIA => "Bulgaria",
            self::ESTONIA => "Estonia",
            self::LITHUANIA => "Lithuania",
            self::ETHIOPIA => "Ethiopia",
            self::YEMEN => "Yemen",
            self::JORDAN => "Jordan",
            self::MADAGASCAR => "Madagascar",
            self::ERITREA => "Eritrea",
            self::IRAQ => "Iraq",
            self::BAHRAIN => "Bahrain",
            self::COMOROS => "Comoros",
            self::TANZANIA => "Tanzania",
            self::DJIBOUTI => "Djibouti",
            self::SOUTH_SUDAN => "South Sudan",
            self::RUSSIA => "Russia",
            self::UGANDA => "Uganda",
            self::SUDAN => "Sudan",
            self::KUWAIT => "Kuwait",
            self::MAYOTTE => "Mayotte",
            self::BELARUS => "Belarus",
            self::SOMALIA => "Somalia",
            self::KENYA => "Kenya",
            self::QATAR => "Qatar",
            self::SAUDI_ARABIA => "Saudi Arabia",
            self::IRAN => "Iran",
            self::AZERBAIJAN => "Azerbaijan",
            self::UNITED_ARAB_EMIRATES => "United Arab Emirates",
            self::SEYCHELLES => "Seychelles",
            self::MAURITIUS => "Mauritius",
            self::OMAN => "Oman",
            self::REUNION => "Réunion",
            self::GEORGIA => "Georgia",
            self::ARMENIA => "Armenia",
            self::AFGHANISTAN => "Afghanistan",
            self::KAZAKHSTAN => "Kazakhstan",
            self::TURKMENISTAN => "Turkmenistan",
            self::TAJIKISTAN => "Tajikistan",
            self::PAKISTAN => "Pakistan",
            self::FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS => "French Southern and Antarctic Lands",
            self::MALDIVES => "Maldives",
            self::UZBEKISTAN => "Uzbekistan",
            self::SRI_LANKA => "Sri Lanka",
            self::INDIA => "India",
            self::NEPAL => "Nepal",
            self::KYRGYZSTAN => "Kyrgyzstan",
            self::BRITISH_INDIAN_OCEAN_TERRITORY => "British Indian Ocean Territory",
            self::BANGLADESH => "Bangladesh",
            self::BHUTAN => "Bhutan",
            self::COCOS_ISLANDS => "Cocos (Keeling) Islands",
            self::THAILAND => "Thailand",
            self::CHRISTMAS_ISLAND => "Christmas Island",
            self::VIETNAM => "Vietnam",
            self::MONGOLIA => "Mongolia",
            self::INDONESIA => "Indonesia",
            self::CAMBODIA => "Cambodia",
            self::LAOS => "Laos",
            self::BRUNEI => "Brunei",
            self::HONG_KONG => "Hong Kong",
            self::MALAYSIA => "Malaysia",
            self::MACAU => "Macau",
            self::PHILIPPINES => "Philippines",
            self::AUSTRALIA => "Australia",
            self::CHINA => "China",
            self::SINGAPORE => "Singapore",
            self::TAIWAN => "Taiwan",
            self::TIMOR_LESTE => "Timor-Leste",
            self::PALAU => "Palau",
            self::NORTH_KOREA => "North Korea",
            self::SOUTH_KOREA => "South Korea",
            self::JAPAN => "Japan",
            self::MICRONESIA => "Micronesia",
            self::GUAM => "Guam",
            self::PAPUA_NEW_GUINEA => "Papua New Guinea",
            self::NORTHERN_MARIANA_ISLANDS => "Northern Mariana Islands",
            self::VANUATU => "Vanuatu",
            self::SOLOMON_ISLANDS => "Solomon Islands",
            self::NEW_CALEDONIA => "New Caledonia",
            self::NORFOLK_ISLAND => "Norfolk Island",
            self::NEW_ZEALAND => "New Zealand",
            self::FIJI => "Fiji",
            self::TUVALU => "Tuvalu",
            self::MARSHALL_ISLANDS => "Marshall Islands",
            self::NAURU => "Nauru",
            self::KIRIBATI => "Kiribati",
            self::WALLIS_AND_FUTUNA => "Wallis and Futuna",
            self::SAMOA => "Samoa",
            self::TOKELAU => "Tokelau",
            self::TONGA => "Tonga"
        };
    }

    public const EXT_PNG = "png";
    public const EXT_WEBP = "webp";
    public const EXT_SVG = "svg";
    public const EXT_JPEG = "jpeg";
    public const SIZE_20 = 20;
    public const SIZE_40 = 40;
    public const SIZE_80 = 80;
    public const SIZE_160 = 160;
    public const SIZE_320 = 320;
    public const SIZE_640 = 640;
    public const SIZE_1280 = 1280;
    public const SIZE_2560 = 2560;

    /**
     * @param bool $waving
     * @param int $size
     * @param string $extension
     * @return string url
     * @link https://flagpedia.net/download/api
     */
    public function getFlagUrl(bool $waving = false, int $size = self::SIZE_20, string $extension = self::EXT_SVG): string
    {
        $baseUrl = "https://flagcdn.com/";
        if ($extension === self::EXT_SVG) {
            return "{$baseUrl}{$this->value}.{$extension}";
        }
        if ($waving && in_array($extension, [self::EXT_PNG, self::EXT_WEBP])) {
            $xSize = match ($size) {
                self::SIZE_20 => '20x15',
                self::SIZE_40 => '40x30',
                self::SIZE_80 => '80x60',
                self::SIZE_160 => '160x120',
                self::SIZE_320, self::SIZE_640, self::SIZE_1280, self::SIZE_2560 => '256x192',
                default => "16x12"
            };
            return "{$baseUrl}{$xSize}/{$this->value}.{$extension}";
        }
        return "{$baseUrl}w{$size}/{$this->value}.{$extension}";
    }

    public function getTimezone(): string
    {
        return match ($this) {
            self::UNITED_STATES_MINOR_OUTLYING_ISLANDS => 'Pacific/Midway',
            self::NIUE => 'Pacific/Niue',
            self::AMERICAN_SAMOA => 'Pacific/Pago_Pago',
            self::UNITED_STATES => 'America/Adak',
            self::COOK_ISLANDS => 'Pacific/Rarotonga',
            self::FRENCH_POLYNESIA => 'Pacific/Tahiti',
            self::CANADA => 'America/Dawson',
            self::PITCAIRN_ISLANDS => 'Pacific/Pitcairn',
            self::MEXICO => 'America/Tijuana',
            self::BELIZE => 'America/Belize',
            self::COSTA_RICA => 'America/Costa_Rica',
            self::CHILE => 'Pacific/Easter',
            self::EL_SALVADOR => 'America/El_Salvador',
            self::ECUADOR => 'Pacific/Galapagos',
            self::GUATEMALA => 'America/Guatemala',
            self::NICARAGUA => 'America/Managua',
            self::HONDURAS => 'America/Tegucigalpa',
            self::COLOMBIA => 'America/Bogota',
            self::CAYMAN_ISLANDS => 'America/Cayman',
            self::TURKS_AND_CAICOS_ISLANDS => 'America/Grand_Turk',
            self::CUBA => 'America/Havana',
            self::JAMAICA => 'America/Jamaica',
            self::PERU => 'America/Lima',
            self::BAHAMAS => 'America/Nassau',
            self::PANAMA => 'America/Panama',
            self::HAITI => 'America/Port-au-Prince',
            self::VENEZUELA => 'America/Caracas',
            self::ANGUILLA => 'America/Anguilla',
            self::ANTIGUA_AND_BARBUDA => 'America/Antigua',
            self::ARUBA => 'America/Aruba',
            self::PARAGUAY => 'America/Asuncion',
            self::BARBADOS => 'America/Barbados',
            self::BERMUDA => 'Atlantic/Bermuda',
            self::BRAZIL => 'America/Boa_Vista',
            self::CURACAO => 'America/Curacao',
            self::DOMINICA => 'America/Dominica',
            self::GRENADA => 'America/Grenada',
            self::GUADELOUPE => 'America/Guadeloupe',
            self::GUYANA => 'America/Guyana',
            self::CARIBBEAN_NETHERLANDS => 'America/Kralendijk',
            self::BOLIVIA => 'America/La_Paz',
            self::SINT_MAARTEN => 'America/Lower_Princes',
            self::SAINT_MARTIN => 'America/Marigot',
            self::MARTINIQUE => 'America/Martinique',
            self::MONTSERRAT => 'America/Montserrat',
            self::ANTARCTICA => 'Antarctica/Palmer',
            self::TRINIDAD_AND_TOBAGO => 'America/Port_of_Spain',
            self::PUERTO_RICO => 'America/Puerto_Rico',
            self::DOMINICAN_REPUBLIC => 'America/Santo_Domingo',
            self::SAINT_BARTHELEMY => 'America/St_Barthelemy',
            self::SAINT_KITTS_AND_NEVIS => 'America/St_Kitts',
            self::SAINT_LUCIA => 'America/St_Lucia',
            self::UNITED_STATES_VIRGIN_ISLANDS => 'America/St_Thomas',
            self::SAINT_VINCENT_AND_THE_GRENADINES => 'America/St_Vincent',
            self::GREENLAND => 'America/Thule',
            self::BRITISH_VIRGIN_ISLANDS => 'America/Tortola',
            self::ARGENTINA => 'America/Argentina/Buenos_Aires',
            self::FRENCH_GUIANA => 'America/Cayenne',
            self::SAINT_PIERRE_AND_MIQUELON => 'America/Miquelon',
            self::URUGUAY => 'America/Montevideo',
            self::SURINAME => 'America/Paramaribo',
            self::FALKLAND_ISLANDS => 'Atlantic/Stanley',
            self::SOUTH_GEORGIA => 'Atlantic/South_Georgia',
            self::PORTUGAL => 'Atlantic/Azores',
            self::CAPE_VERDE => 'Atlantic/Cape_Verde',
            self::COTE_DIVOIRE => 'Africa/Abidjan',
            self::GHANA => 'Africa/Accra',
            self::MALI => 'Africa/Bamako',
            self::GAMBIA => 'Africa/Banjul',
            self::GUINEA_BISSAU => 'Africa/Bissau',
            self::SPAIN => 'Atlantic/Canary',
            self::MOROCCO => 'Africa/Casablanca',
            self::GUINEA => 'Africa/Conakry',
            self::SENEGAL => 'Africa/Dakar',
            self::IRELAND => 'Europe/Dublin',
            self::WESTERN_SAHARA => 'Africa/El_Aaiun',
            self::FAROE_ISLANDS => 'Atlantic/Faroe',
            self::SIERRA_LEONE => 'Africa/Freetown',
            self::GUERNSEY => 'Europe/Guernsey',
            self::ISLE_OF_MAN => 'Europe/Isle_of_Man',
            self::JERSEY => 'Europe/Jersey',
            self::TOGO => 'Africa/Lome',
            self::UNITED_KINGDOM, self::ENGLAND, self::NORTHERN_IRELAND, self::SCOTLAND, self::WALES => 'Europe/London',
            self::LIBERIA => 'Africa/Monrovia',
            self::MAURITANIA => 'Africa/Nouakchott',
            self::BURKINA_FASO => 'Africa/Ouagadougou',
            self::ICELAND => 'Atlantic/Reykjavik',
            self::SAO_TOME_AND_PRINCIPE => 'Africa/Sao_Tome',
            self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA => 'Atlantic/St_Helena',
            self::ALGERIA => 'Africa/Algiers',
            self::NETHERLANDS => 'Europe/Amsterdam',
            self::ANDORRA => 'Europe/Andorra',
            self::CENTRAL_AFRICAN_REPUBLIC => 'Africa/Bangui',
            self::SERBIA => 'Europe/Belgrade',
            self::GERMANY => 'Europe/Berlin',
            self::SLOVAKIA => 'Europe/Bratislava',
            self::REPUBLIC_OF_THE_CONGO => 'Africa/Brazzaville',
            self::BELGIUM => 'Europe/Brussels',
            self::HUNGARY => 'Europe/Budapest',
            self::DENMARK => 'Europe/Copenhagen',
            self::CAMEROON => 'Africa/Douala',
            self::GIBRALTAR => 'Europe/Gibraltar',
            self::DR_CONGO => 'Africa/Kinshasa',
            self::NIGERIA => 'Africa/Lagos',
            self::GABON => 'Africa/Libreville',
            self::SLOVENIA => 'Europe/Ljubljana',
            self::SVALBARD_AND_JAN_MAYEN => 'Arctic/Longyearbyen',
            self::ANGOLA => 'Africa/Luanda',
            self::LUXEMBOURG => 'Europe/Luxembourg',
            self::EQUATORIAL_GUINEA => 'Africa/Malabo',
            self::MALTA => 'Europe/Malta',
            self::MONACO => 'Europe/Monaco',
            self::CHAD => 'Africa/Ndjamena',
            self::NIGER => 'Africa/Niamey',
            self::NORWAY => 'Europe/Oslo',
            self::FRANCE => 'Europe/Paris',
            self::MONTENEGRO => 'Europe/Podgorica',
            self::BENIN => 'Africa/Porto-Novo',
            self::CZECHIA => 'Europe/Prague',
            self::ITALY => 'Europe/Rome',
            self::SAN_MARINO => 'Europe/San_Marino',
            self::BOSNIA_AND_HERZEGOVINA => 'Europe/Sarajevo',
            self::NORTH_MACEDONIA => 'Europe/Skopje',
            self::SWEDEN => 'Europe/Stockholm',
            self::ALBANIA => 'Europe/Tirane',
            self::LIBYA => 'Africa/Tripoli',
            self::TUNISIA => 'Africa/Tunis',
            self::LIECHTENSTEIN => 'Europe/Vaduz',
            self::VATICAN_CITY => 'Europe/Vatican',
            self::AUSTRIA => 'Europe/Vienna',
            self::POLAND => 'Europe/Warsaw',
            self::NAMIBIA => 'Africa/Windhoek',
            self::CROATIA => 'Europe/Zagreb',
            self::SWITZERLAND => 'Europe/Zurich',
            self::GREECE => 'Europe/Athens',
            self::LEBANON => 'Asia/Beirut',
            self::MALAWI => 'Africa/Blantyre',
            self::ROMANIA => 'Europe/Bucharest',
            self::BURUNDI => 'Africa/Bujumbura',
            self::EGYPT => 'Africa/Cairo',
            self::MOLDOVA => 'Europe/Chisinau',
            self::SYRIA => 'Asia/Damascus',
            self::BOTSWANA => 'Africa/Gaborone',
            self::PALESTINE => 'Asia/Gaza',
            self::ZIMBABWE => 'Africa/Harare',
            self::FINLAND => 'Europe/Helsinki',
            self::TURKEY => 'Europe/Istanbul',
            self::ISRAEL => 'Asia/Jerusalem',
            self::SOUTH_AFRICA => 'Africa/Johannesburg',
            self::RWANDA => 'Africa/Kigali',
            self::ZAMBIA => 'Africa/Lusaka',
            self::MOZAMBIQUE => 'Africa/Maputo',
            self::ALAND_ISLANDS => 'Europe/Mariehamn',
            self::LESOTHO => 'Africa/Maseru',
            self::ESWATINI => 'Africa/Mbabane',
            self::CYPRUS => 'Asia/Nicosia',
            self::LATVIA => 'Europe/Riga',
            self::UKRAINE => 'Europe/Simferopol',
            self::BULGARIA => 'Europe/Sofia',
            self::ESTONIA => 'Europe/Tallinn',
            self::LITHUANIA => 'Europe/Vilnius',
            self::ETHIOPIA => 'Africa/Addis_Ababa',
            self::YEMEN => 'Asia/Aden',
            self::JORDAN => 'Asia/Amman',
            self::MADAGASCAR => 'Indian/Antananarivo',
            self::ERITREA => 'Africa/Asmara',
            self::IRAQ => 'Asia/Baghdad',
            self::BAHRAIN => 'Asia/Bahrain',
            self::COMOROS => 'Indian/Comoro',
            self::TANZANIA => 'Africa/Dar_es_Salaam',
            self::DJIBOUTI => 'Africa/Djibouti',
            self::SOUTH_SUDAN => 'Africa/Juba',
            self::RUSSIA => 'Europe/Kaliningrad',
            self::UGANDA => 'Africa/Kampala',
            self::SUDAN => 'Africa/Khartoum',
            self::KUWAIT => 'Asia/Kuwait',
            self::MAYOTTE => 'Indian/Mayotte',
            self::BELARUS => 'Europe/Minsk',
            self::SOMALIA => 'Africa/Mogadishu',
            self::KENYA => 'Africa/Nairobi',
            self::QATAR => 'Asia/Qatar',
            self::SAUDI_ARABIA => 'Asia/Riyadh',
            self::IRAN => 'Asia/Tehran',
            self::AZERBAIJAN => 'Asia/Baku',
            self::UNITED_ARAB_EMIRATES => 'Asia/Dubai',
            self::SEYCHELLES => 'Indian/Mahe',
            self::MAURITIUS => 'Indian/Mauritius',
            self::OMAN => 'Asia/Muscat',
            self::REUNION => 'Indian/Reunion',
            self::GEORGIA => 'Asia/Tbilisi',
            self::ARMENIA => 'Asia/Yerevan',
            self::AFGHANISTAN => 'Asia/Kabul',
            self::KAZAKHSTAN => 'Asia/Aqtau',
            self::TURKMENISTAN => 'Asia/Ashgabat',
            self::TAJIKISTAN => 'Asia/Dushanbe',
            self::PAKISTAN => 'Asia/Karachi',
            self::FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS => 'Indian/Kerguelen',
            self::MALDIVES => 'Indian/Maldives',
            self::UZBEKISTAN => 'Asia/Samarkand',
            self::SRI_LANKA => 'Asia/Colombo',
            self::INDIA => 'Asia/Kolkata',
            self::NEPAL => 'Asia/Kathmandu',
            self::KYRGYZSTAN => 'Asia/Bishkek',
            self::BRITISH_INDIAN_OCEAN_TERRITORY => 'Indian/Chagos',
            self::BANGLADESH => 'Asia/Dhaka',
            self::BHUTAN => 'Asia/Thimphu',
            self::COCOS_ISLANDS => 'Indian/Cocos',
            self::THAILAND => 'Asia/Bangkok',
            self::CHRISTMAS_ISLAND => 'Indian/Christmas',
            self::VIETNAM => 'Asia/Ho_Chi_Minh',
            self::MONGOLIA => 'Asia/Hovd',
            self::INDONESIA => 'Asia/Jakarta',
            self::CAMBODIA => 'Asia/Phnom_Penh',
            self::LAOS => 'Asia/Vientiane',
            self::BRUNEI => 'Asia/Brunei',
            self::HONG_KONG => 'Asia/Hong_Kong',
            self::MALAYSIA => 'Asia/Kuala_Lumpur',
            self::MACAU => 'Asia/Macau',
            self::PHILIPPINES => 'Asia/Manila',
            self::AUSTRALIA => 'Australia/Perth',
            self::CHINA => 'Asia/Shanghai',
            self::SINGAPORE => 'Asia/Singapore',
            self::TAIWAN => 'Asia/Taipei',
            self::TIMOR_LESTE => 'Asia/Dili',
            self::PALAU => 'Pacific/Palau',
            self::NORTH_KOREA => 'Asia/Pyongyang',
            self::SOUTH_KOREA => 'Asia/Seoul',
            self::JAPAN => 'Asia/Tokyo',
            self::MICRONESIA => 'Pacific/Chuuk',
            self::GUAM => 'Pacific/Guam',
            self::PAPUA_NEW_GUINEA => 'Pacific/Port_Moresby',
            self::NORTHERN_MARIANA_ISLANDS => 'Pacific/Saipan',
            self::VANUATU => 'Pacific/Efate',
            self::SOLOMON_ISLANDS => 'Pacific/Guadalcanal',
            self::NEW_CALEDONIA => 'Pacific/Noumea',
            self::NORFOLK_ISLAND => 'Pacific/Norfolk',
            self::NEW_ZEALAND => 'Pacific/Auckland',
            self::FIJI => 'Pacific/Fiji',
            self::TUVALU => 'Pacific/Funafuti',
            self::MARSHALL_ISLANDS => 'Pacific/Kwajalein',
            self::NAURU => 'Pacific/Nauru',
            self::KIRIBATI => 'Pacific/Tarawa',
            self::WALLIS_AND_FUTUNA => 'Pacific/Wallis',
            self::SAMOA => 'Pacific/Apia',
            self::TOKELAU => 'Pacific/Fakaofo',
            self::TONGA => 'Pacific/Tongatapu'
        };
    }

    public function getUtcOffsetInSeconds(): int
    {
       $dtz = new DateTimeZone($this->getTimezone());
       return $dtz->getOffset(new DateTime());
    }
}